language: objective-c
osx_image: xcode8
xcode_project: CounterExample.xcodeproj
xcode_scheme: CounterExample
xcode_sdk: iphonesimulator10.0
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
install:
    - carthage bootstrap --no-use-binaries --platform iOS
script: xcodebuild test -project CounterExample.xcodeproj -scheme CounterExample -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'